export const db = "main-stackflow"
export const questionCollection = "question"
export const answerCollection = "answer"
export const commentCollection = "comment"
export const voteCollection = "votes"
export const questionAttachmentBucket = "question-attachment"